# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestCurator:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_curator(self):
        self.driver.get("http://localhost:5000/")
        self.driver.set_window_size(1854, 891)
        self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user2@example.com")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(8) .align-middle:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .feather-eye").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .feather-download").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .feather-edit").click()
        self.driver.find_element(By.ID, "title").click()
        self.driver.find_element(By.ID, "title").send_keys("Dataset with author 1 editado")
        dropdown = self.driver.find_element(By.ID, "publication_type")
        dropdown.find_element(By.XPATH, "//option[. = 'Journal Article']").click()
        self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(4)").click()
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) form .feather").click()
        assert self.driver.switch_to.alert.text == "Are you sure?"
        self.driver.switch_to.alert.accept()
