# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestseleniumexploredates():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testseleniumexploredates(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1854, 1048)
    self.driver.find_element(By.LINK_TEXT, "Explore").click()
    self.driver.find_element(By.ID, "date_after").click()
    self.driver.find_element(By.ID, "date_after").send_keys("2025-10-01")
    self.driver.find_element(By.ID, "date_after").click()
    self.driver.find_element(By.ID, "date_after").send_keys("2024-10-01")
    self.driver.find_element(By.CSS_SELECTOR, ".col-12:nth-child(3) > .mb-3").click()
    self.driver.find_element(By.ID, "date_after").click()
    self.driver.find_element(By.ID, "date_before").click()
    self.driver.find_element(By.ID, "date_before").send_keys("2025-09-30")
    self.driver.find_element(By.ID, "date_before").click()
    self.driver.find_element(By.ID, "date_after").click()
    self.driver.find_element(By.ID, "date_after").click()
    self.driver.find_element(By.ID, "date_after").send_keys("2025-08-27")
    self.driver.find_element(By.ID, "clear-filters").click()
  
