# Generated by Selenium IDE
from modulefinder import test
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from core.selenium.common import close_driver, initialize_driver


class TestSeleniumExplore():
  def setup_method(self, method):
    self.driver = initialize_driver()
    self.vars = {}

  def teardown_method(self, method):
    close_driver(self.driver)


  def test_selenium_explore(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1854, 1048)
    self.driver.find_element(By.LINK_TEXT, "Explore").click()
    self.driver.find_element(By.ID, "query").click()
    self.driver.find_element(By.ID, "query").send_keys("dataset")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "query").send_keys("author 1")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "query").send_keys("tag6")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "date_after").click()
    self.driver.find_element(By.ID, "date_after").send_keys("2025-11-24")
    self.driver.find_element(By.ID, "date_after").click()
    self.driver.find_element(By.ID, "date_after").click()
    self.driver.find_element(By.ID, "clear-filters").click()
    self.driver.find_element(By.ID, "date_before").click()
    self.driver.find_element(By.ID, "date_before").send_keys("2025-11-28")
    self.driver.find_element(By.ID, "date_after").click()
    self.driver.find_element(By.ID, "date_after").send_keys("2025-09-29")
    self.driver.find_element(By.ID, "clear-filters").click()
    element = self.driver.find_element(By.ID, "clear-filters")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "select2-author-container").click()
    self.driver.find_element(By.ID, "select2-author-container").click()
    self.driver.find_element(By.ID, "select2-author-container").click()
    self.driver.find_element(By.ID, "select2-author-container").click()
    self.driver.find_element(By.ID, "select2-author-container").click()


if __name__ == "__main__":
    test_instance = TestSeleniumExplore()
    test_instance.setup_method(None)
    try:
        test_instance.test_selenium_explore()
        print("✓ Test passed!")
    except Exception as e:
        print(f"✗ Test failed: {e}")
    finally:
        test_instance.teardown_method(None)