# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestseleniumexploreauthor():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testseleniumexploreauthor(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1854, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(3) .align-middle:nth-child(2)").click()
    self.driver.find_element(By.ID, "select2-author-container").click()
    self.driver.find_element(By.ID, "select2-author-container").click()
    self.driver.find_element(By.ID, "select2-author-container").click()
    self.driver.find_element(By.ID, "select2-author-container").click()
    self.driver.find_element(By.ID, "select2-author-container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search--dropdown > .select2-search__field").click()
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search--dropdown > .select2-search__field").send_keys("Author 7")
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search--dropdown > .select2-search__field").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "select2-author-container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-12:nth-child(4)").click()
    self.driver.find_element(By.ID, "select2-author-container").click()
  
