# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestseleniumexplorequery():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testseleniumexplorequery(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1854, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(3) .align-middle:nth-child(2)").click()
    self.driver.find_element(By.ID, "query").click()
    self.driver.find_element(By.ID, "query").send_keys("tag3")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "query").send_keys("author")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "query").send_keys("dataset")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "query").send_keys("author 1")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "query").send_keys("author 7")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
  
