# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestseleniumexplorepubtype():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testseleniumexplorepubtype(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1854, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(3) .align-middle:nth-child(2)").click()
    self.driver.find_element(By.ID, "publication_type").click()
    dropdown = self.driver.find_element(By.ID, "publication_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Observation Data']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#publication_type > option:nth-child(3)").click()
    dropdown = self.driver.find_element(By.ID, "publication_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Journal Article']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#publication_type > option:nth-child(5)").click()
    dropdown = self.driver.find_element(By.ID, "publication_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Software']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(9)").click()
    dropdown = self.driver.find_element(By.ID, "publication_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Thesis']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(8)").click()
    dropdown = self.driver.find_element(By.ID, "publication_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Preprint']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#publication_type > option:nth-child(6)").click()
    self.driver.find_element(By.ID, "publication_type").click()
    dropdown = self.driver.find_element(By.ID, "publication_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Technical Report']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(7)").click()
    dropdown = self.driver.find_element(By.ID, "publication_type")
    dropdown.find_element(By.XPATH, "//option[. = 'None']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#publication_type > option:nth-child(2)").click()
    dropdown = self.driver.find_element(By.ID, "publication_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Observation Data']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#publication_type > option:nth-child(3)").click()
    dropdown = self.driver.find_element(By.ID, "publication_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Data Paper']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#publication_type > option:nth-child(4)").click()
    self.driver.find_element(By.ID, "clear-filters").click()
  
