# Generated by Selenium IDE
import time

import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

from app import create_app, db
from app.modules.auth.models import User
from app.modules.auth.services import AuthenticationService
from app.modules.profile.models import UserProfile
from app.modules.token.services import TokenService
from core.environment.host import get_host_for_selenium_testing
from core.selenium.common import close_driver, initialize_driver

NAME = "Peter"
SURNAME = "Pan"
EMAIL = "peterpan@yahoo.com"
PASSWORD = "elalola"


def create_test_user():
    """Create a user for Selenium tests in the DEVELOPMENT database."""
    app = create_app("development")
    with app.app_context():
        auth_service = AuthenticationService()
        existing_user = User.query.filter_by(email=EMAIL).first()
        if not existing_user:
            user = auth_service.create_with_profile(name=NAME, surname=SURNAME, email=EMAIL, password=PASSWORD)
            db.session.commit()
            return user.id
        return existing_user.id


def cleanup_test_user(user_id):
    """Cleanup test user from database."""
    app = create_app("development")
    with app.app_context():
        user = User.query.get(user_id)
        if user:
            TokenService().revoke_all_tokens_for_user(user.id)
            profile = UserProfile.query.filter_by(user_id=user.id).first()
            if profile:
                db.session.delete(profile)
            db.session.delete(user)
            db.session.commit()


def test_getSessions():
    driver = initialize_driver()
    try:
        host = get_host_for_selenium_testing()
        driver.get(f"{host}/")
        driver.set_window_size(1051, 797)
        driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
        driver.find_element(By.ID, "email").click()
        driver.find_element(By.ID, "email").send_keys(EMAIL)
        driver.find_element(By.ID, "password").click()
        driver.find_element(By.ID, "password").send_keys(PASSWORD)
        driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
        time.sleep(2)
        driver.find_element(By.LINK_TEXT, "Pan, Peter").click()
        driver.find_element(By.LINK_TEXT, "My profile").click()
        driver.find_element(By.CSS_SELECTOR, ".btn").click()
        time.sleep(2)
        current_session_badge = driver.find_element(By.CSS_SELECTOR, "span.badge.bg-success.ms-1")
        assert current_session_badge.text == "Current Session"
        print("test_getSessions passed!")
    except Exception as e:
        print(f"test_getSessions failed: {e}")
        raise
    finally:
        close_driver(driver)


def test_revokeToken():
    driver = initialize_driver()
    try:
        host = get_host_for_selenium_testing()
        driver.get(f"{host}/")
        driver.set_window_size(1552, 832)
        driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
        driver.find_element(By.ID, "email").click()
        driver.find_element(By.ID, "email").send_keys(EMAIL)
        driver.find_element(By.ID, "password").click()
        driver.find_element(By.ID, "password").send_keys(PASSWORD)
        driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
        driver.find_element(By.LINK_TEXT, "My profile").click()
        driver.find_element(By.CSS_SELECTOR, ".btn").click()
        driver.find_element(By.CSS_SELECTOR, ".btn-sm").click()
        assert driver.switch_to.alert.text == "Are you sure you want to revoke this session?"
        driver.switch_to.alert.accept()
        print("test_revokeToken passed!")
    except Exception as e:
        print(f"test_revokeToken failed: {e}")
        raise
    finally:
        close_driver(driver)


def test_revokeAllTokens():
    driver = initialize_driver()
    try:
        host = get_host_for_selenium_testing()
        driver.get(f"{host}/")
        driver.set_window_size(1051, 797)
        driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
        driver.find_element(By.ID, "email").click()
        driver.find_element(By.ID, "email").send_keys(EMAIL)
        driver.find_element(By.ID, "password").send_keys(PASSWORD)
        driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
        driver.find_element(By.LINK_TEXT, "My profile").click()
        driver.find_element(By.CSS_SELECTOR, ".btn").click()
        driver.find_element(By.CSS_SELECTOR, ".mt-3 > .btn").click()
        assert (
            driver.switch_to.alert.text
            == "Are you sure you want to revoke ALL sessions? You will be logged out :("
        )
        driver.switch_to.alert.accept()
        print("test_revokeAllTokens passed!")
    except Exception as e:
        print(f"test_revokeAllTokens failed: {e}")
        raise
    finally:
        close_driver(driver)


if __name__ == "__main__":
    user_id = create_test_user()
    
    try:
        test_getSessions()
        test_revokeToken()
        test_revokeAllTokens()
    finally:
        cleanup_test_user(user_id)